### ISSUE TITLE
"error while upscaling"

### ISSUE THREAD

**Issue by nottooloud** [Djdefrag/QualityScaler#20]
QualityScaler 4.1.f
NVIDIA GeForce GTX 1660 Ti 6 GB Win 10
Tried all models, CPU&GPU, limited RAM, several files including logo.png from your install package.
Makes a pile of PNGs and then comes back error while upscaling.
Is there an informative log somewhere?

**Comment by nottooloud** [comment]
Extracted the directory and ran the .exe in that directory. Program runs, accepts drag and drop files, produces the intermediate files, and then errors out.

**Comment by Djdefrag** [comment]
try to extract again the .zip with 7zip and check in the directory if there are 3 files:
BSRGANx2.pth
BSRGANx4.pth
RealSR_JPEGx4.pth

**Comment by nottooloud** [comment]
All present and accounted for.

**Comment by Djdefrag** [comment]
Strange, in next release i will add better error message. 

I think could be a driver problem, a windows 10 too old, or no permission to read and write files...

Sorry :(

**Comment by Djdefrag** [comment]
what driver version do you have?

**Comment by nottooloud** [comment]
NVIDIA driver? The current Game Ready, 526.47. Win10 is up to date. The program is reading and writing files.
Informative error messages would be useful.

**Comment by nottooloud** [comment]
Hmm, that's interesting. I tried run as administrator and drag and drop stopped working.

**Comment by Djdefrag** [comment]
Hi, sorry to bother again. 
I have another question, when upscaling Qualitysaler will produce an image named with *_resized.png. 
Can you please check if this file is created and if there is a watermark on it?

**Comment by nottooloud** [comment]
Yes, and yes. Says Upscaled with etc etc.

**Comment by Djdefrag** [comment]
Okok thanks, I thought that QualityScaler was not finding the font file for applying the watermark, but it seems not :(

**Comment by Djdefrag** [comment]
Hi, sorry to bother you again. 
Did you have installed Visual C++ Redistributable ? 

If not, here is a .zip with all packages 
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/   
:)

**Comment by nottooloud** [comment]
install_all.bat. 
Oh Good. A whole bunch of random Windows installs. God, I hate this operating system.
Fine, let's go.
Welp, no change.

**Comment by Djdefrag** [comment]
:(

**Comment by nottooloud** [comment]
Ran that install. DXDIAG says DirectX 12 with no problems found.

**Comment by Djdefrag** [comment]
I thank you from the bottom of my heart for your support. At this point I don't know which way to turn anymore. 

:(

Maybe it may be some problem in the compilation phase or something, and I have no control over that.

**Comment by nottooloud** [comment]
Time to write in some error logging?

**Comment by Djdefrag** [comment]
yes

**Comment by JadoreHC** [comment]
Hello, I am another user having this issue. I was about to purchase the software but then decided to do trial instead and see the results  and compare to Topaz. I installed trial version and when i run it, i see that the software resizes the photos, splits them into 9 images but when it is about to upscale, I receive "error while upscaling". If this gets fixed and the results are good, im happy to move to paid version.

Note, when i downloaded the zip file, and unpacked it, Windows 11 blocked the .exe file saying it contains Trojan Horse. I had to disable firewall and then proceeded with running the app. But not sure if Windows was still not somehow blocking the upscaling. Thanks

**Comment by Djdefrag** [comment]
Hi @JadoreHC ,

1. yes, there is a resize option to reduce the time to upscale an image: of course the more you shrink the photo, the less the quality of the upscale will be (by default it is 70%) 
2. qualityscaler cut the image when it does not fit in VRAM/RAM limit (default is 8 GB)
3. so something is not working with communication beetween gpu and pytorch: 

- [ ] What are your pc specs? 
- [ ] Did you followed the readme and installed DirectX and Visual C Redistributable? 
- [ ] Or maibe Windows defender is blocking the app, just disable to try this pls (I cannot try because the actually Windows i use does not have Defender preinstalled). 

Let me know so i can better undestand the problem :)

Unfortunately the false positive of the antivirus is the fault of the library used to package the Python code in .exe - https://www.reddit.com/r/learnpython/comments/sidi10/pyinstaller_exe_is_labeled_as_a_trojan_by_avg/

Thank you :)

**Comment by JadoreHC** [comment]
Hi, 

thanks for the swift response :) very kind of you... my pc has 32 GB RAM and I also had DirectX and Visual C installed.

I have tried your advice and left the default resize to 70% (300p pic to 200p) and the upscale went through (in 7 sec.). I did some testing for different size pictures and the maximum size the software can handle is 200p (either height or width). Anything above will crash ("error while upscaling". Since i was testing 700p-1000p pics, i could compare upscaled pics to their reference and see how precise it was... Some results were interesting but due to downsizing, a lot of artifacts were lost. I upscale videos and for Topaz Upscaling, my PC can handle 720p-1080p videos and for Interpolation, Dain app can interpolate 578p videos and Rife App 1080p videos. Do you think your app will be able to handle bigger formats without crashing? Not sure what RAM i would need to be able to upscale bigger videos, in your references, you even have 4k vids. 

Thank you very much for your help. Glad the program is working now :)

**Comment by nottooloud** [comment]
Good find. Confirmed, works with images 200 pixels and under. That should be a help in the troubleshooting.

**Comment by Djdefrag** [comment]
Hi @nottooloud @JadoreHC thank you very much for your valuable feedback :D

Abolutely your rig is capable of upscale any kind of image and video, any directx12 gpu can works well (i've tested rx 570 and gtx 1660) so must be a Pytorch problem, i hope they release a fix in a short time. 

In the meantime I will put more exhaustive logs and with more information so as to better understand what happens :)

**Comment by Djdefrag** [comment]
@nottooloud @JadoreHC Hi, i just released new update 6.0 with error log improvement. If someone can test it maibe we can understand why it fails :)

Thank you in advance :)

**Comment by nottooloud** [comment]
6.0 works here. No error. Absolutely enormous file, 3.6mb PNG 100% scaled came out 88MB instead of the expected 15 or so, but I can always compress it with another program.

**Comment by JadoreHC** [comment]
Im still getting errors in 6.0 it says to check the .log file but not sure where the .log file is located? I do not see it in QualityScaler folder or the folder where the upscaled pic is located

**Comment by Djdefrag** [comment]
is located in QualityScaler folder, there is a QualityScaler.log :)

**Comment by JadoreHC** [comment]
oh thanks. i used search engine and it didnt pick up extensions... i found the log. this is the error (small 200x200 pics still work, but bigger ones don't - even if software splits them into 9 smaller pics)

Error while upscaling

CHECK failed: ((((HRESULT)((d3d_device->CreateCommittedResource( &properties, D3D12_HEAP_FLAG_NONE, &resource_buffer, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, __uuidof(*out), reinterpret_cast<void**>(out))))) >= 0)) == (true):

**Comment by Djdefrag** [comment]
Mh, strange error; can you tell me your pc full spec? :)

**Comment by JadoreHC** [comment]
Sure, here you go... thanks in advance
![PC](https://user-images.githubusercontent.com/118090178/202850142-ad520aaa-ef52-4724-bac2-dfb78aa78a8a.jpg)

**Comment by Djdefrag** [comment]
Thank you!
I think i found the problem. Actually QualityScaler is trying to use your Intel GPU instead of your Nvidia gpu. To resolve this issue you should go in Windows Settings > Graphic settrings > Add QualityScaler.exe > Options > Select Nvidia gpu :

![202654622-2d0f6c79-5b8e-4431-9813-24da29514e5b](https://user-images.githubusercontent.com/32263112/202851546-efafcc49-64fa-4543-98b6-641eb1ca7183.png)
![202654755-518bcaa5-96e8-4798-bbc7-5d5101fc655e](https://user-images.githubusercontent.com/32263112/202851552-270a2c0a-a70d-4536-b63f-8a7000b330ee.png)

Let me know if this fix the issue :) Thank you!

**Comment by JadoreHC** [comment]
oh wow. this worked like a charm! thank you so much :) works perfectly now :)

**Comment by Djdefrag** [comment]
Nice!! 

Next release will support multi gpu system like your with the possibility to choose the gpu :D
